---
title: "Vital Signs (Part B) - weekly"
output: html_document
---

```{r declarations, echo=FALSE, warning=FALSE, message = FALSE}
# Load the libraries
library(knitr)
library(rmarkdown)
library(dplyr)
library(lubridate)
library(qcc)
library(tseries)
library(forecast)
library(ggplot2)

opts_chunk$set(dev = "png", fig.path = "/home/greig/R-projects/Vital_Signs")

# load the data
ALOS.raw <- read.csv("/home/greig/R-projects/Vital_Signs/VS_ALOS.csv", header = TRUE, stringsAsFactors = FALSE, check.names = TRUE, strip.white = TRUE, na.strings = c("", "NULL", "NA"))

ALOS <- ALOS.raw

# declare the variables
ALOS$DDATE <- as.Date(ALOS$DDATE)
ALOS$EPISODE <- as.factor(ALOS$EPISODE)
ALOS$FACILITY <- as.factor(ALOS$FACILITY)
ALOS$ADMAGE <- as.integer(ALOS$ADMAGE)
ALOS$GENDER <- as.factor(ALOS$GENDER)
ALOS$ETHGROUP <-  as.factor(ALOS$ETHGROUP)
ALOS$DOMTLA <- as.factor(ALOS$DOMTLA)
ALOS$DOMDHB <- as.factor(ALOS$DOMDHB)
ALOS$DOMCODE <- as.factor(ALOS$DOMCODE)
ALOS$SPECIALTY <- as.factor(ALOS$SPECIALTY)
ALOS$ARRANGED <- as.factor(ALOS$ARRANGED)
ALOS$LOS <- as.integer(ALOS$LOS)
ALOS$LINE <- as.factor(ALOS$LINE)
ALOS$DRGCODE <- as.factor(ALOS$DRGCODE)
ALOS$PRINCIPLDIAGNOSISCODE <- as.factor(ALOS$PRINCIPLDIAGNOSISCODE)

ALOS <- ALOS %>% 
  mutate(Week = week(DDATE), Month = month(DDATE), Year = year(DDATE))

ALOS <- ALOS %>% 
  filter(DDATE < "2016-06-02 00:00:00")
```

# Weekly Synopsis 


The weekly version of Vital signs (Part B) is focused on admissions over the week prior and the average length of stay. More detail is provided regarding services driving either process, or projects of the Operation Sustainability team.

# Whole of system measures

```{r MCH, warning=FALSE, message = FALSE, comment="", results="hide"}

MCH <- ALOS %>% 
  filter(LINE != "Emergency" & LINE != "Mental Health")

totMCH <- MCH %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

m_MCH <- select(totMCH, Mean)
ewma(m_MCH, title = "ALOS for CSB", xlab = "Weeks since 1.Jan.2010", ylab = "ALOS")

c_MCH <- select(totMCH, Count)
ewma(c_MCH,  title = "Admissions / week for CSB", xlab = "Weeks since 1.Jan.2010", ylab = "Admissions / week")
tsMCH <- ts(c_MCH, frequency = 52, start = 2010)
tsMCH.dec1 <- decompose(tsMCH, type = "additive")
plot(tsMCH.dec1)
#tsMCH.res <- na.contiguous(tsMCH.dec1$random)
#ewma(tsMCH.res)
#tsMCH.dec2 <- decompose(tsMCH.dec1$random, type = "additive")
#plot(tsMCH.dec2)
#tsMCH.res2 <- na.contiguous(tsMCH.dec2$random)
#ewma(tsMCH.res2)

#tsMCH.arima <- auto.arima(tsMCH, 
#                          stationary = TRUE, 
#                          seasonal = TRUE)
#tsMCH.fc2 <- forecast.Arima(tsMCH.arima, 
#                            h=26)
#plot(tsMCH.fc2)
#summary(tsMCH.fc2)

tsMCH.hwl <- HoltWinters(tsMCH, 
                         beta = NULL,
                         gamma = NULL, 
                         seasonal = "multiplicative")
tsMCH.fc3 <- forecast.HoltWinters(tsMCH.hwl,
                                  h=26)
plot(tsMCH.fc3)
summary(tsMCH.fc3)

MCH2 <- ALOS %>% 
  filter(LINE != "Emergency" & DDATE >= "2014-01-01 00:00:00")

totMCH2 <- MCH2 %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()


c_totMCH2 <- select(totMCH2, Count)

tsMCH2 <- ts(c_totMCH2, frequency = 52, start = 2014)
#tsEM.dec2 <- decompose(tsEM2, type = "additive")
#plot(tsEM2.dec1)

tsMCH2.hwl <- HoltWinters(tsMCH2, 
                         beta = NULL,
                         gamma = NULL, 
                         seasonal = "multiplicative")
tsMCH2.fc3 <- forecast.HoltWinters(tsMCH2.hwl,
                                  h=26)
plot(tsMCH2.fc3)


#tsMCH.res2 <- residuals(tsMCH.arima)
#acf(tsMCH.res2)
#pacf(tsMCH.res2)

#check.resid <- as.numeric(tsMCH.res2)
#check.fit <- fitted.Arima(tsMCH.arima)
#plot(check.resid~check.fit, pch = 16, cex = 0.5)
#abline(h=2, col =2)

#qqnorm(check.resid)
#qqline(check.resid)
#ewma(tsMCH.res2)

```

-----  

```{r timeProjections, echo=FALSE, warning=FALSE, message = FALSE, comment=""}
#summary(tsMCH.fc2)
```

-----

# Emergency Department

```{r EM, echo=FALSE, warning=FALSE, message = FALSE, comment="", results = "hide"}

EM <- ALOS %>% 
  filter(ARRANGED == "Acute" & LINE == "Emergency")

totEM <- EM %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

m_totEM <- select(totEM, Mean)
ewma(m_totEM, title = "ALOS for Emergency Department admissions", xlab = "Weeks since 1.Jan.2010", ylab = "ALOS")
c_totEM <- select(totEM, Count)
ewma(c_totEM,  title = "Admissions / week for Emergency Department", xlab = "Weeks since 1.Jan.2010", ylab = "Admissions / week")

tsEM <- ts(c_totEM, frequency = 52, start = 2010)
tsEM.dec1 <- decompose(tsEM, type = "additive")
plot(tsEM.dec1)

#tsEM.arima <- auto.arima(tsEM, stationary = TRUE, seasonal = TRUE)
#tsEM.fc2 <- forecast.Arima(tsEM.arima, h=26)
#plot(tsEM.fc2)
#summary(tsEM.fc2)

#tsEM.res <- na.contiguous(tsEM.dec1$random)
#ewma(tsEM.res)

tsEM.hwl <- HoltWinters(tsEM, 
                         beta = NULL,
                         gamma = NULL, 
                         seasonal = "multiplicative")
tsEM.fc3 <- forecast.HoltWinters(tsEM.hwl,
                                  h=26)
plot(tsEM.fc3)

EM2 <- ALOS %>% 
  filter(ARRANGED == "Acute" & LINE == "Emergency" & DDATE >= "2014-01-01 00:00:00")

totEM2 <- EM2 %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()


c_totEM2 <- select(totEM2, Count)

tsEM2 <- ts(c_totEM2, frequency = 52, start = 2014)
#tsEM.dec2 <- decompose(tsEM2, type = "additive")
#plot(tsEM2.dec1)

tsEM2.hwl <- HoltWinters(tsEM2, 
                         beta = NULL,
                         gamma = NULL, 
                         seasonal = "multiplicative")
tsEM2.fc3 <- forecast.HoltWinters(tsEM2.hwl,
                                  h=26)
plot(tsEM2.fc3)

```


-----  

# General Medicine
This is a significant service from both an admission rate and an ALOS perspective

```{r GenMed_ALOS, echo=FALSE, warning=FALSE, message = FALSE, results="hide"}
GenMed <- ALOS %>% 
  filter(ARRANGED == "Acute" & SPECIALTY == "General Internal Medical Services")

totGenMed <- GenMed %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

m_totGenMed <- select(totGenMed, Mean)
ewma(m_totGenMed, title = "ALOS for acute General Medicine", xlab = "Weeks since 1.Jan.2010", ylab = "ALOS")

c_totGenMed <- select(totGenMed, Count)
ewma(c_totGenMed,  title = "Admissions / week for acute General Medicine", xlab = "Weeks since 1.Jan.2010", ylab = "Admissions / week")

tsGenMed <- ts(c_totGenMed, frequency = 52, start = 2010)
tsGenMed.dec1 <- decompose(tsGenMed, type = "additive")
plot(tsGenMed.dec1)
#tsGenMed.res <- na.contiguous(tsGenMed.dec1$random)
#ewma(tsGenMed.res)

LS_GenMed <- GenMed %>% 
  filter(LOS>10)

LS_Med <- LS_GenMed %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

cLS_Med <- select(LS_Med, Count)
ewma(cLS_Med, title = "Number of patients admitted/week with LOS >10 days", xlab = "weeks since 1.Jan.2010", ylab = "admissions / week")
ts_cLS_Med <- ts(cLS_Med, frequency = 52, start = 2010)
tsLS_Med.dec1 <- decompose(ts_cLS_Med, type = "additive")
plot(tsLS_Med.dec1)

IS_GenMed <- GenMed %>% 
  filter(LOS <= 10 & LOS >= 6)

IS_Med <- IS_GenMed %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

cIS_Med <- select(IS_Med, Count)
ewma(cIS_Med, title = "Number of patients admitted/week with LOS 6-9 days", xlab = "weeks since 1.Jan.2010", ylab = "admissions / week")
ts_cIS_Med <- ts(cIS_Med, frequency = 52, start = 2010)
tsIS_Med.dec1 <- decompose(ts_cIS_Med, type = "additive")
plot(tsIS_Med.dec1)

MS_GenMed <- GenMed %>% 
  filter(LOS <= 5 & LOS >= 2)

MS_Med <- MS_GenMed %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

cMS_Med <- select(MS_Med, Count)
ewma(cMS_Med, title = "Number of patients admitted/week with LOS 2-5 days", xlab = "weeks since 1.Jan.2010", ylab = "admissions / week")
ts_cMS_Med <- ts(cMS_Med, frequency = 52, start = 2010)
tsMS_Med.dec1 <- decompose(ts_cMS_Med, type = "additive")
plot(tsMS_Med.dec1)

SS_GenMed <- GenMed %>% 
  filter(LOS<2)

SS_Med <- SS_GenMed %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

cSS_Med <- select(SS_Med, Count)
ewma(cSS_Med, title = "Number of patients admitted/week with LOS < 2days", xlab = "weeks since 1.Jan.2010", ylab = "admissions / week")
ts_cSS_Med <- ts(cSS_Med, frequency = 52, start = 2010)
tsSS_Med.dec1 <- decompose(ts_cSS_Med, type = "additive")
plot(tsSS_Med.dec1)
```

-----  

```{r GenSurg, echo=FALSE, warning=FALSE, message = FALSE, results="hide"}

# General Surgery ALOS & Count
GenSurg <- ALOS %>% 
  filter(ARRANGED == "Acute" & SPECIALTY == "General Surgical Services")

totGenSurg <- GenSurg %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

m_totGenSurg <- select(totGenSurg, Mean)
ewma(m_totGenSurg, title = "ALOS for acute General Surgery", xlab = "Weeks since 1.Jan.2010", ylab = "ALOS")
c_totGenSurg <- select(totGenSurg, Count)
ewma(c_totGenSurg,  title = "Admissions / week for acute General Surgery", xlab = "Weeks since 1.Jan.2010", ylab = "Admissions / week")

tsGenSurg <- ts(c_totGenSurg, frequency = 52, start = 2010)
tsGenSurg.dec1 <- decompose(tsGenSurg, type = "additive")
plot(tsGenSurg.dec1)

UGenSurg <- ALOS %>% 
  filter(ARRANGED == "Acute" & SPECIALTY == "General Surgical Services" & LOS>=5)

LSGenSurg <- UGenSurg %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

m_LSGenSurg <- select(LSGenSurg, Mean)
ewma(m_LSGenSurg, title = "ALOS for long stay acute General Surgery", xlab = "Weeks since 1.Jan.2010", ylab = "ALOS")
c_LSGenSurg <- select(LSGenSurg, Count)
ewma(c_LSGenSurg,  title = "Acute Gen Surgery admissions / week who stay >= 5 days", xlab = "Weeks since 1.Jan.2010", ylab = "Admissions / week")

ts_LSGenSurg <- ts(c_LSGenSurg, frequency = 52, start = 2010)
ts_LSGenSurg.dec1 <- decompose(ts_LSGenSurg, type = "additive")
plot(ts_LSGenSurg.dec1)

SGenSurg <- ALOS %>% 
  filter(ARRANGED == "Acute" & SPECIALTY == "General Surgical Services" & LOS < 5)

SSGenSurg <- SGenSurg %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

m_SSGenSurg <- select(SSGenSurg, Mean)
ewma(m_SSGenSurg, title = "ALOS for short stay acute General Surgery", xlab = "Weeks since 1.Jan.2010", ylab = "ALOS")
c_SSGenSurg <- select(SSGenSurg, Count)
ewma(c_SSGenSurg,  title = "Acute Gen Surgery admissions / week < 5 days", xlab = "Weeks since 1.Jan.2010", ylab = "Admissions / week")

ts_SSGenSurg <- ts(c_SSGenSurg, frequency = 52, start = 2010)
ts_SSGenSurg.dec1 <- decompose(ts_SSGenSurg, type = "additive")
plot(ts_SSGenSurg.dec1)

```

-----

# Orthopaedics 

```{r ortho, echo=FALSE, warning=FALSE, message = FALSE, comment="", results='hide'}

# Ortho
Ortho <- ALOS %>% 
  filter(SPECIALTY == "Orthopaedic Services")

totOrtho <- Ortho %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

m_totOrtho <- select(totOrtho, Mean)
ewma(m_totOrtho, title = "ALOS for Orthopaedic Surgery", xlab = "Weeks since 1.Jan.2010", ylab = "ALOS")
c_totOrtho <- select(totOrtho, Count)
ewma(c_totOrtho,  title = "Admissions / week for Orthopaedic Surgery", xlab = "Weeks since 1.Jan.2010", ylab = "Admissions / week")

tsOrtho <- ts(c_totOrtho, frequency = 52, start = 2010)
tsOrtho.dec1 <- decompose(tsOrtho, type = "additive")
plot(tsOrtho.dec1)

# Count for Acute Ortho
acuteOrtho <- ALOS %>% 
  filter(ARRANGED == "Acute" & SPECIALTY == "Orthopaedic Services")

tot_acuteOrtho <- acuteOrtho %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

m_totacuteOrtho <- select(tot_acuteOrtho, Mean)
ewma(m_totacuteOrtho, title = "ALOS for acute Orthopaedic Surgery", xlab = "Weeks since 1.Jan.2010", ylab = "ALOS")
c_totacuteOrtho <- select(tot_acuteOrtho, Count)
ewma(c_totacuteOrtho,  title = "Admissions / week for acute Orthopaedic Surgery", xlab = "Weeks since 1.Jan.2010", ylab = "Admissions / week")

tsacuteOrtho <- ts(c_totacuteOrtho, frequency = 52, start = 2010)
tsacuteOrtho.dec1 <- decompose(tsacuteOrtho, type = "additive")
plot(tsacuteOrtho.dec1)

```


-----

# ElderHealth

```{r elderhealth, echo=FALSE, warning=FALSE, message = FALSE, comment="", results='hide'}

EH <- ALOS %>% 
  filter(LINE == "Elderly")

totEH <- EH %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

m_totEH <- select(totEH, Mean)
ewma(m_totEH, title = "ALOS for Elder Health", xlab = "Weeks since 1.Jan.2010", ylab = "ALOS")

tsEHm <- ts(m_totEH, frequency = 52, start = 2010)
tsEHm.dec1 <- decompose(tsEHm, type = "additive")
plot(tsEHm.dec1)

c_totEH <- select(totEH, Count)
ewma(c_totEH,  title = "Admissions / week for Elder Health", xlab = "Weeks since 1.Jan.2010", ylab = "Admissions / week")

tsEH <- ts(c_totEH, frequency = 52, start = 2010)
tsEH.dec1 <- decompose(tsEH, type = "additive")
plot(tsEH.dec1)

```

-----

# Mental Health

```{r MentalHealth, echo=FALSE, warning=FALSE, message = FALSE, comment="", results='hide'}

MH <- ALOS %>% 
  filter(LINE == "Mental Health")

totMH <- MH %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

m_totMH <- select(totMH, Mean)
ewma(m_totMH, title = "ALOS for Mental Health", xlab = "Weeks since 1.Jan.2010", ylab = "ALOS")
c_totMH <- select(totMH, Count)
ewma(c_totMH,  title = "Admissions / week for Mental Health", xlab = "Weeks since 1.Jan.2010", ylab = "Admissions / week")

tsMH <- ts(c_totMH, frequency = 52, start = 2010)
tsMH.dec1 <- decompose(tsMH, type = "additive")
plot(tsMH.dec1)

```

-----  

# Child Health

```{r paeds, echo=FALSE, warning=FALSE, message = FALSE, comment="", results='hide'}

Paed <- ALOS %>% 
  filter(ARRANGED == "Acute" & LINE == "Paediatric")

totPaed <- Paed %>% 
  group_by(Year, Week) %>% 
  summarise(Mean = mean(LOS, na.rm = TRUE), Count = n()) %>% 
  ungroup()

m_totPaed <- select(totPaed, Mean)
ewma(m_totPaed, title = "ALOS for acute Child Health admissions", xlab = "Weeks since 1.Jan.2010", ylab = "ALOS")
c_totPaed <- select(totPaed, Count)
ewma(c_totPaed,  title = "Admissions / week for acute Child Health admissions", xlab = "Weeks since 1.Jan.2010", ylab = "Admissions / week")

tsPaed <- ts(c_totPaed, frequency = 52, start = 2010)
tsPaed.dec1 <- decompose(tsPaed, type = "additive")
plot(tsPaed.dec1)
```

